import 'package:control_repository/control_repository.dart';
import 'package:test/test.dart';

void main() {
  group('GyverLampMode', () {
    test('fromIndex returns correct mode', () {
      expect(
        GyverLampMode.fromIndex(0),
        equals(GyverLampMode.sparkles),
      );
      expect(
        GyverLampMode.fromIndex(1),
        equals(GyverLampMode.fire),
      );
      expect(
        GyverLampMode.fromIndex(2),
        equals(GyverLampMode.rainbowVertical),
      );
      expect(
        GyverLampMode.fromIndex(3),
        equals(GyverLampMode.rainbowHorizontal),
      );
      expect(
        GyverLampMode.fromIndex(4),
        equals(GyverLampMode.colors),
      );
      expect(
        GyverLampMode.fromIndex(5),
        equals(GyverLampMode.madness),
      );
      expect(
        GyverLampMode.fromIndex(6),
        equals(GyverLampMode.cloud),
      );
      expect(
        GyverLampMode.fromIndex(7),
        equals(GyverLampMode.lava),
      );
      expect(
        GyverLampMode.fromIndex(8),
        equals(GyverLampMode.plasma),
      );
      expect(
        GyverLampMode.fromIndex(9),
        equals(GyverLampMode.rainbow),
      );
      expect(
        GyverLampMode.fromIndex(10),
        equals(GyverLampMode.rainbowStripes),
      );
      expect(
        GyverLampMode.fromIndex(11),
        equals(GyverLampMode.zebra),
      );
      expect(
        GyverLampMode.fromIndex(12),
        equals(GyverLampMode.forest),
      );
      expect(
        GyverLampMode.fromIndex(13),
        equals(GyverLampMode.ocean),
      );
      expect(
        GyverLampMode.fromIndex(14),
        equals(GyverLampMode.color),
      );
      expect(
        GyverLampMode.fromIndex(15),
        equals(GyverLampMode.snow),
      );
      expect(
        GyverLampMode.fromIndex(16),
        equals(GyverLampMode.matrix),
      );
      expect(
        GyverLampMode.fromIndex(17),
        equals(GyverLampMode.fireflies),
      );
    });
  });
}
