include: package:very_good_analysis/analysis_options.10.0.0.yaml

formatter:
  trailing_commas: preserve

linter:
  rules:
    public_member_api_docs: false

analyzer:
  errors:
    avoid_catches_without_on_clauses: ignore
    discarded_futures: ignore
