name: control_repository
description: Repository to control the Gyver Lamp.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  equatable: ^2.0.5
  gyver_lamp_client:
    path: ../gyver_lamp_client
  meta: ^1.9.1

dev_dependencies:
  fake_async: 1.3.1 
  mocktail: 1.0.0
  test: 1.24.4
  very_good_analysis: 5.1.0
